files:
  - source: /sdk/src/main/res/values/strings.xml
    translation: /sdk/src/main/res/values-%locale%/strings.xml
    languages_mapping:
      locale:
        fr: fr
        de: de
        pt-BR: pt-rBR
        es-ES: es-rES
        it: it
